"""Supervisor configuration generation for tempo-devnet."""

from __future__ import annotations

import configparser
import json
from pathlib import Path

import jsonmerge
import tomlkit
import yaml

from .config import DevnetConfig, ValidatorConfig
from .ports import (
    authrpc_port,
    consensus_metrics_port,
    consensus_p2p_port,
    execution_p2p_port,
    http_rpc_port,
    ws_rpc_port,
)

SUPERVISOR_CONFIG_FILE = "supervisord.ini"
LOCALNET_SIGNING_KEY_SECRET = "tempo-localnet-signing-key-secret"


COMMON_PROG_OPTIONS: dict[str, str] = {
    "autostart": "true",
    "autorestart": "true",
    "redirect_stderr": "true",
    "startsecs": "3",
    "stopwaitsecs": "10",
}

# Port offset: 0=consensus-p2p, 1=execution-p2p, 2=metrics, 3=authrpc, 4=http, 5=ws
# Hard-code a generous default so nodes don't overlap
_BASE_PORT_STEP = 10


def _trusted_peers(config: DevnetConfig, data_dir: Path) -> list[str]:
    """Build trusted-peers list from enode identity files."""
    peers: list[str] = []
    for val in config.validators:
        enode_identity_file = data_dir / val.dir_name / "enode.identity"
        if not enode_identity_file.exists():
            continue
        exec_port = execution_p2p_port(val.base_port)
        peers.append(f"enode://{enode_identity_file.read_text().strip()}@{val.host}:{exec_port}")
    return peers


def write_secret_file(val_dir: Path) -> Path:
    """Write the signing-key passphrase to a ``.secret`` file in the node dir.

    Returns the path to the secret file.
    """
    secret_path = val_dir / ".secret"
    secret_path.write_text(LOCALNET_SIGNING_KEY_SECRET)
    return secret_path


def _build_node_args(
    *,
    tempo_bin: str,
    p2p_host: str,
    rpc_host: str,
    host: str,
    base_port: int,
    genesis_path: str,
    datadir: str,
    signing_key: str,
    signing_share: str,
    secret_file: str,
    enode_key: str,
    trusted_peers: list[str],
    extra_flags: list[str] | None = None,
) -> list[str]:
    """Build the argument list for ``tempo node``.

    Args:
        p2p_host: IP to bind the consensus P2P listener.
        rpc_host: IP to bind HTTP/WS JSON-RPC.
        host: Advertised IP for metrics and trusted-peers.
    """
    peers_str = ",".join(trusted_peers)

    args: list[str] = [
        tempo_bin,
        "node",
        "--consensus.signing-key",
        signing_key,
        "--consensus.secret",
        secret_file,
        "--consensus.signing-share",
        signing_share,
        "--consensus.listen-address",
        f"{p2p_host}:{consensus_p2p_port(base_port)}",
        "--consensus.metrics-address",
        f"{host}:{consensus_metrics_port(base_port)}",
        "--chain",
        genesis_path,
        "--datadir",
        datadir,
        "--port",
        str(execution_p2p_port(base_port)),
        "--discovery.port",
        str(execution_p2p_port(base_port)),
        "--p2p-secret-key",
        enode_key,
        "--trusted-peers",
        peers_str,
        "--authrpc.port",
        str(authrpc_port(base_port)),
        "--http",
        "--http.addr",
        rpc_host,
        "--http.port",
        str(http_rpc_port(base_port)),
        "--http.api",
        "all",
        "--ws",
        "--ws.addr",
        rpc_host,
        "--ws.port",
        str(ws_rpc_port(base_port)),
        "--consensus.use-local-defaults",
        "--consensus.allow-private-ips",
    ]

    if extra_flags:
        args.extend(extra_flags)

    return args


def write_run_script(
    val_dir: Path,
    node_args: list[str],
) -> Path:
    """Write a ``run.sh`` wrapper script that exec's the node command.

    The script uses ``exec`` so the supervisor process is replaced by the
    node process directly, keeping PID tracking clean.

    Args:
        val_dir: Node directory to write the script into.
        node_args: Full argument list for ``tempo node ...``.

    Returns:
        Path to the generated ``run.sh``.
    """
    dst = val_dir / "run.sh"

    # multi-line format: first token (binary) on exec line, then one flag per line
    binary = _sh_quote(node_args[0])
    arg_lines = " \\\n".join("  " + _sh_quote(a) for a in node_args[1:])

    script = f"""\
#!/bin/sh
# auto-generated by tempo-devnet — {val_dir.name}

cd "$(dirname "$0")"

exec {binary} \\\n{arg_lines}
"""
    dst.write_text(script)
    dst.chmod(0o755)
    return dst


def _sh_quote(s: str) -> str:
    """Minimal shell quoting — wrap in single quotes, escaping embedded single quotes."""
    return "'" + s.replace("'", "'\\''") + "'"


def apply_genesis_patch(data_dir: Path, patch: dict) -> None:
    """Deep-merge a patch dict into ``genesis.json``.

    Args:
        data_dir: Root directory containing ``genesis.json``.
        patch: Dict of genesis fields to override (deep-merged).
    """
    if not patch:
        return

    genesis_path = data_dir / "genesis.json"
    if not genesis_path.exists():
        return

    with open(genesis_path) as f:
        genesis = json.load(f)

    genesis = jsonmerge.merge(genesis, patch)

    with open(genesis_path, "w") as f:
        json.dump(genesis, f, indent=2)

    print(f"  patched genesis.json with {len(patch)} top-level key(s)")


def write_reth_config(val_dir: Path, patch: dict) -> None:
    """Write a ``reth.toml`` config file into a node's data directory.

    Uses ``tomlkit`` for proper TOML serialization.  Only non-empty patches
    produce output.

    Args:
        val_dir: Node data directory.
        patch: Dict of reth config options.
    """
    if not patch:
        return

    reth_path = val_dir / "reth.toml"
    with open(reth_path, "w") as f:
        tomlkit.dump(patch, f)
    print(f"  wrote reth.toml to {val_dir.name}/")


def generate_supervisor_config(
    config: DevnetConfig,
    data_dir: Path,
    *,
    force: bool = False,
) -> Path:
    """Generate a supervisor configuration file for all validator nodes.

    Also writes:
    - A ``.secret`` passphrase file inside each node directory.
    - A ``run.sh`` wrapper script that exec's the node command.
    - ``reth.toml`` per node if ``config.patch_reth`` is set.
    - Patches ``genesis.json`` if ``config.patch_genesis`` is set.

    The supervisor command is an absolute path to ``run.sh``.

    Args:
        config: The devnet configuration.
        data_dir: Root directory containing genesis.json and validator dirs.
        force: Overwrite existing supervisor config.

    Returns:
        Path to the generated ``supervisord.ini`` file.
    """
    data_dir = data_dir.resolve()

    # Apply genesis patch first
    apply_genesis_patch(data_dir, config.patch_genesis)

    # Copy patched genesis into each validator directory for isolation
    genesis_src = data_dir / "genesis.json"
    if genesis_src.exists():
        for val in config.validators:
            (data_dir / val.dir_name / "genesis.json").write_bytes(genesis_src.read_bytes())

    dst = data_dir / SUPERVISOR_CONFIG_FILE
    if dst.exists() and not force:
        return dst

    tempo_bin = config.tempo_bin

    ini = configparser.RawConfigParser()
    ini.add_section("supervisord")
    ini["supervisord"] = {
        "pidfile": f"{data_dir}/supervisord.pid",
        "nodaemon": "true",
        "logfile": f"{data_dir}/supervisord.log",
        "logfile_maxbytes": "0",
        "strip_ansi": "true",
    }

    ini.add_section("rpcinterface:supervisor")
    ini["rpcinterface:supervisor"] = {
        "supervisor.rpcinterface_factory": "supervisor.rpcinterface:make_main_rpcinterface",
    }

    sock = data_dir / "supervisor.sock"
    ini.add_section("unix_http_server")
    ini["unix_http_server"] = {"file": str(sock)}

    ini.add_section("supervisorctl")
    ini["supervisorctl"] = {"serverurl": f"unix://{sock}"}

    # Derive trusted peers from enode identity files
    peers = _trusted_peers(config, data_dir)

    for val in config.validators:
        val_dir = data_dir / val.dir_name
        prgname = f"program:{val.dir_name}"
        ini.add_section(prgname)

        # Write the secret file for --consensus.secret
        write_secret_file(val_dir)

        # All paths are relative — the wrapper script cds to the node dir first
        node_args = _build_node_args(
            tempo_bin=tempo_bin,
            p2p_host=val.p2p_host,
            rpc_host=val.rpc_host,
            host=val.host,
            base_port=val.base_port,
            genesis_path="./genesis.json",
            datadir=".",
            signing_key="./signing.key",
            signing_share="./signing.share",
            secret_file="./.secret",
            enode_key="./enode.key",
            trusted_peers=peers,
            extra_flags=config.patch_node_flags or None,
        )

        # Write the wrapper script
        write_run_script(val_dir, node_args)

        # Write per-node reth config
        write_reth_config(val_dir, config.patch_reth)

        # Supervisor runs the wrapper script via absolute path.
        # Using an absolute path avoids issues with supervisor's execve
        # (no shell involved) and the working directory.
        ini[prgname] = dict(
            COMMON_PROG_OPTIONS,
            directory=str(val_dir),
            command=str(val_dir / "run.sh"),
            stdout_logfile=f"{val_dir}/node.log",
        )

    with open(dst, "w") as fp:
        ini.write(fp)

    return dst


DOCKER_CONFIG_FILE = "docker-compose.yml"
CONTAINER_DATA_DIR = "/data"

# Fixed internal ports for Docker containers — each container has its own
# network namespace so they can all use the same port numbers.
_DOCKER_CONSENSUS_P2P = 8000
_DOCKER_EXECUTION_P2P = 8001
_DOCKER_CONSENSUS_METRICS = 8002
_DOCKER_AUTHRPC = 8003
_DOCKER_HTTP_RPC = 8004
_DOCKER_WS_RPC = 8005


def _docker_node_command(
    config: DevnetConfig,
    val: ValidatorConfig,
    data_dir: Path,
) -> list[str]:
    """Build the ``tempo node`` argument list for a Docker container.

    All file paths are relative — ``docker-run.sh`` first cds to
    ``/data/<moniker>``.  Uses fixed internal ports (each container has
    its own network namespace).  Trusted-peers use Docker service names.
    """
    # Build trusted-peers with Docker service names (fixed internal port)
    peers: list[str] = []
    for other in config.validators:
        if other.moniker == val.moniker:
            continue
        enode_id_file = data_dir / other.dir_name / "enode.identity"
        if not enode_id_file.exists():
            continue
        peers.append(f"enode://{enode_id_file.read_text().strip()}@{other.moniker}:{_DOCKER_EXECUTION_P2P}")

    peers_str = ",".join(peers)

    args: list[str] = [
        config.tempo_bin,
        "node",
        "--consensus.signing-key",
        "./signing.key",
        "--consensus.secret",
        "./.secret",
        "--consensus.signing-share",
        "./signing.share",
        "--consensus.listen-address",
        f"0.0.0.0:{_DOCKER_CONSENSUS_P2P}",
        "--consensus.metrics-address",
        f"0.0.0.0:{_DOCKER_CONSENSUS_METRICS}",
        "--chain",
        "./genesis.json",
        "--datadir",
        ".",
        "--port",
        str(_DOCKER_EXECUTION_P2P),
        "--discovery.port",
        str(_DOCKER_EXECUTION_P2P),
        "--p2p-secret-key",
        "./enode.key",
        "--trusted-peers",
        peers_str,
        "--authrpc.port",
        str(_DOCKER_AUTHRPC),
        "--http",
        "--http.addr",
        "0.0.0.0",
        "--http.port",
        str(_DOCKER_HTTP_RPC),
        "--http.api",
        "all",
        "--ws",
        "--ws.addr",
        "0.0.0.0",
        "--ws.port",
        str(_DOCKER_WS_RPC),
        "--consensus.use-local-defaults",
        "--consensus.allow-private-ips",
        "--tempo.bootnodes-endpoint",
        "none",
    ]

    if config.patch_node_flags:
        args.extend(config.patch_node_flags)

    return args


def write_docker_run_script(val_dir: Path, node_args: list[str]) -> Path:
    """Write a ``docker-run.sh`` wrapper script using container-relative paths.

    The script lives inside the node directory and is invoked inside the
    Docker container where ``/data`` is mounted.
    """
    dst = val_dir / "docker-run.sh"
    binary = _sh_quote(node_args[0])
    arg_lines = " \\\n".join("  " + _sh_quote(a) for a in node_args[1:])
    script = f"""\
#!/bin/sh
# auto-generated by tempo-devnet — {val_dir.name} (docker)

cd "$(dirname "$0")"

exec {binary} \\\n{arg_lines}
"""
    dst.write_text(script)
    dst.chmod(0o755)
    return dst


def generate_docker_compose(
    config: DevnetConfig,
    data_dir: Path,
    *,
    force: bool = False,
) -> Path:
    """Generate a ``docker-compose.yml`` to run the devnet in Docker.

    Each validator runs in a separate container on an isolated bridge
    network.  P2P traffic stays inside the Docker network; RPC/WS ports
    are published to the host for external full nodes.

    A ``docker-run.sh`` wrapper script is written into each validator
    directory; the docker-compose command calls it via the mounted volume.

    Requires the tempo Docker image specified in ``config.docker_image``.
    """
    dst = data_dir / DOCKER_CONFIG_FILE
    if dst.exists() and not force:
        return dst

    services: dict[str, dict] = {}

    for val in config.validators:
        svc_name = val.moniker
        val_dir = data_dir / val.dir_name

        # Generate docker-specific wrapper script with container paths
        node_args = _docker_node_command(config, val, data_dir)
        write_docker_run_script(val_dir, node_args)

        # Container command points to the wrapper inside the mounted volume
        container_script = f"{CONTAINER_DATA_DIR}/{val.dir_name}/docker-run.sh"

        published_ports: list[str] = []
        # Host port = base_port + offset, container port = fixed internal port
        for port_offset, container_port in [
            (3, _DOCKER_AUTHRPC),
            (4, _DOCKER_HTTP_RPC),
            (5, _DOCKER_WS_RPC),
        ]:
            host_port = val.base_port + port_offset
            published_ports.append(f"{host_port}:{container_port}")

        services[svc_name] = {
            "image": config.docker_image,
            "command": container_script,
            "volumes": [f"{data_dir}:{CONTAINER_DATA_DIR}"],
            "ports": published_ports,
            "networks": [config.docker_network],
        }

    compose: dict = {
        "services": services,
        "networks": {
            config.docker_network: {
                "driver": "bridge",
            },
        },
    }

    with open(dst, "w") as f:
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

    print(f"  wrote docker-compose.yml ({len(config.validators)} services)")
    return dst
